include(cmake/nuttx_kconfig.cmake)

set(SOURCE_FILE ${CMAKE_ARGV3})
set(TARGET_FILE ${CMAKE_ARGV4})

file(STRINGS ${SOURCE_FILE} ConfigContents)
encode_brackets(ConfigContents)

foreach(NameAndValue ${ConfigContents})
  decode_brackets(NameAndValue)
  encode_semicolon(NameAndValue)
  if("${NameAndValue}" MATCHES "CONFIG_ARCH="
     OR "${NameAndValue}" MATCHES "^CONFIG_ARCH_CHIP_"
     OR "${NameAndValue}" MATCHES "CONFIG_ARCH_CHIP="
     OR "${NameAndValue}" MATCHES "CONFIG_ARCH_BOARD="
     OR "${NameAndValue}" MATCHES "^CONFIG_ARCH_CUSTOM"
     OR "${NameAndValue}" MATCHES "^CONFIG_ARCH_BOARD_CUSTOM")
    decode_semicolon(Value)
    file(APPEND ${TARGET_FILE} "${NameAndValue}\n")
  endif()
endforeach()

get_filename_component(BINARY_DIR "${TARGET_FILE}" DIRECTORY)

set(OUTPUT_FILE ${BINARY_DIR}/defconfig)

# cmake-format: off
file(WRITE ${OUTPUT_FILE} "")
file(APPEND ${OUTPUT_FILE} "\#\n")
file(APPEND ${OUTPUT_FILE} "\# This file is autogenerated: PLEASE DO NOT EDIT IT.\n")
file(APPEND ${OUTPUT_FILE} "\#\n")
file(APPEND ${OUTPUT_FILE} "\# You can use \"make menuconfig\" to make any modifications to the installed .config file.\n")
file(APPEND ${OUTPUT_FILE} "\# You can then do \"make savedefconfig\" to generate a new defconfig file that includes your\n")
file(APPEND ${OUTPUT_FILE} "\# modifications.\n")
file(APPEND ${OUTPUT_FILE} "\#\n")
file(READ ${TARGET_FILE} CONTENTS)
# cmake-format: on
encode_brackets(CONTENTS)
encode_semicolon(CONTENTS)

string(REGEX MATCHALL "[^\n]+" LINES ${CONTENTS})

list(REMOVE_DUPLICATES LINES)
list(SORT LINES)

foreach(LINE IN LISTS LINES)
  decode_brackets(LINE)
  decode_semicolon(LINE)
  file(APPEND ${OUTPUT_FILE} "${LINE}\n")
endforeach()

execute_process(COMMAND ${CMAKE_COMMAND} -E remove ${TARGET_FILE})
